//Schneider Electric - 2017-01-25
//created by Markus Wiedenmaier, practice-innovation
//        2017-01-2015

//this is a placeholder script file.
//do not edit this file. Content or file is replaced when landing pages are generated for certain web helps